project:
  type: book

book:
  title: "Online experiments"
  author: Fabian Gunzinger
  # date: "2/12/2024"
  chapters:
    - index.md
    - part: Introduction
      chapters:
      - chapters/introduction.md # For now, I discuss here larger questions such as why stats in business, and causal inference vs prediction.
    - part: chapters/statistics.md
      chapters:
      - chapters/stats_of_online_experiments.md
      - chapters/outcomes.md
      - chapters/standard_error.md
      - chapters/testing_and_cis.md
      - chapters/power.md
      - chapters/analysis.md
    - part: chapters/practice.md
      chapters:
        - chapters/threats_to_validity.qmd
        # - chapters/important_topics.md
        # - chapters/guiding_principles.qmd
        # - chapters/metrics.md
        # - chapters/experiment_configuration.md
        # - chapters/decision_making.qmd
        # - chapters/threats_to_validity.qmd
        # - chapters/practical_issues.qmd
        # - chapters/variance_reduction.qmd
        # - chapters/network_experiments.qmd
        # - chapters/heterogeneous_treatment_effects.qmd
        # - chapters/long_term_effects.md
        # - chapters/triggered_analysis.md
        # - chapters/sequential_testing.md
        # - chapters/multiple_hypothesis_correction.qmd
        # - chapters/multi_arm_bandits.md

    # - part: "Designs"
    # Discussion of experiment designs used in practice
        # - chapters/experiment_designs.md
    - part: chapters/philosophy.md
      chapters: 
      - chapters/limitations_criticism.md

        # - chapters/ethics.qmd

    - part: chapters/platforms.md
      chapters:
        # - chapters/platform_architecture_at_jet.md
        - chapters/data_architecture.md
        - chapters/examples.md

    - part: "Appendices"
      chapters:

        - chapters/quasi_experiments.qmd
    # move this to above chapter    
     #     - chapters/matching.qmd
    #     - chapters/regression_discontinuity.qmd

        - chapters/assignment_mechanism.md
        - chapters/notes_on_athey2017econometrics.md
        - chapters/stats_foundations.md
        - chapters/proof.md
      # - chapters/projection.md
      # - chapters/fwl.qmd
      # - chapters/stats_details_like_lln_and_clt.qmd

      # - chapters/regression.qmd
      # - chapters/regression_for_experiments.qmd
      
      # - chapters/fisher.qmd
      # - chapters/neyman.md
      # - chapters/treatment_effects.md

      # - chapters/history.qmd
      # - chapters/alternative_approaches.qmd
      # - chapters/useful_resources.qmd
      # - chapters/references.qmd

bibliography: /Users/fgunzinger/.dotfiles/latex/fabib.bib


format:
  html:
    theme: cosmo
    css: custom.scss



